#!/bin/sh

exec > /var/log/late_command.log 2>&1

set -x

. /etc/default/locale
jockey-text -a --no-dbus
apt-get install --yes $(check-language-support)
oem-config-prepare --quiet
wget http://fourdollars.github.com/d-i/precise/sources.list -O /etc/apt/sources.list
